services:
  db:
    image: docker.io/library/postgres:17-alpine
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: urlshortener
      SPRING_DATASOURCE_PASSWORD: urlshortener
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
volumes:
  postgres_data: